[package]
name = "rust_algos"
version = "0.1.0"
authors = ["Yi Feng Yang <yifeng@yfyang.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
